Repository demos-europe/demosplan-ui, pull requests merged in 2023-03, with the labels that each got.

#111 bug(refs: T31449): fix checkbox positioning in user list
  src/components/core/DpTableCardList/DpTableCardListHeader.vue
Labels: frontend

#104 feat(refs T31492): refactor editor
  CHANGELOG.md
  src/components/core/DpEditor/DpBoilerPlate.stories.mdx
  src/components/core/DpEditor/DpBoilerPlate.vue
  src/components/core/DpEditor/DpBoilerPlateModal.stories.mdx
  src/components/core/DpEditor/DpBoilerPlateModal.vue
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/DpRecommendationModal.stories.mdx
  src/components/core/DpEditor/DpRecommendationModal.vue
  src/components/core/DpEditor/DpRecommendationModal/DpInsertableRecommendation.vue
Labels: enhancement, frontend

#114 Feature: make demosplan UI available in addons
  CHANGELOG.md
  webpack.config.js
Labels: enhancement, frontend

#132 fix: Remove empty file
  src/components/core/DpEditor/DpBoilerPlateModal.vue
Labels: bug

#133 fix(refs T31929): Make DpDatepicker loadable
  src/components/DpDatepicker/DpDatepicker.vue
Labels: bug
