Repository demos-europe/demosplan-ui, pull requests merged in 2023-09, with the labels that each got.

#491 chore: add DpStickyElement to Storybook.
  CHANGELOG.md
  src/components/DpStickyElement/DpStickyElement.stories.mdx
  src/components/DpStickyElement/DpStickyElement.stories.tsx
Labels: documentation

#504 chore: add DpSlidingPagination to Storybook.
  CHANGELOG.md
  src/components/DpSlidingPagination/DpSlidingPagination.stories.mdx
  src/components/DpSlidingPagination/DpSlidingPagination.stories.tsx
Labels: documentation

#497 chore: add DpDraggable to Storybook.
  CHANGELOG.md
  src/components/DpDraggable/DpDraggable.stories.mdx
  src/components/DpDraggable/DpDraggable.stories.tsx
Labels: documentation

#505 chore: add DpTooltip to Storybook.
  CHANGELOG.md
  src/components/DpTooltip/DpTooltip.stories.mdx
  src/components/DpTooltip/DpTooltip.stories.tsx
Labels: documentation

#511 fix(refs T34566): Pass propper Values to init Tooltips
  src/components/DpTooltip/utils/tooltip.js
  src/directives/Tooltip/Tooltip.js
Labels: bug

#512 fix(refs T34571): Shorten Delay for destroytooltip
  src/components/DpTooltip/utils/tooltip.js
Labels: bug

#516 chore: add Props to DpUpload & DpUploadFiles.
  CHANGELOG.md
  src/components/core/DpUpload/DpUpload.vue
  src/components/core/DpUpload/DpUploadFiles.vue
  src/components/core/DpUpload/utils/UppyTranslations.js
  src/components/shared/translations.js
Labels: bug, enhancement, review:frontend

#492 chore: add DpSearchField to Storybook.
  CHANGELOG.md
  src/components/DpSearchField/DpSearchField.stories.mdx
  src/components/DpSearchField/DpSearchField.stories.tsx
  src/components/DpSearchField/DpSearchField.vue
Labels: documentation

#380 chore (refs T33878): Add DpTextArea to Storybook.
  CHANGELOG.md
  src/components/DpTextArea/DpTextArea.stories.mdx
  src/components/DpTextArea/DpTextArea.stories.tsx
Labels: documentation, review:frontend

#518 chore: add DpUploadFiles to Storybook.
  CHANGELOG.md
  src/components/core/DpUpload/DpUploadFiles.stories.mdx
  src/components/core/DpUpload/DpUploadFiles.stories.tsx
  src/components/core/DpUpload/DpUploadFiles.vue
Labels: documentation

#521 chore: add DpDatepicker to Storybook.
  src/components/DpDatepicker/DpDatepicker.stories.mdx
  src/components/DpDatepicker/DpDatepicker.stories.tsx
  src/components/DpDatepicker/DpDatepicker.vue
Labels: documentation

#526 chore: add DpButtonIcon to Storybook.
  CHANGELOG.md
  src/components/DpButtonIcon/DpButtonIcon.stories.mdx
  src/components/DpButtonIcon/DpButtonIcon.stories.tsx
  src/components/DpButtonIcon/DpButtonIcon.vue
Labels: documentation

#525 chore: add DpTimePicker to Storybook.
  CHANGELOG.md
  src/components/DpTimePicker/DpTimePicker.stories.mdx
  src/components/DpTimePicker/DpTimePicker.stories.tsx
Labels: documentation

#531 chore: add DpProgressBar to Storybook.
  CHANGELOG.md
  src/components/DpProgressBar/DpProgressBar.stories.mdx
  src/components/DpProgressBar/DpProgressBar.stories.tsx
Labels: documentation

#536 chore (refs T33326): Move DpToggleForm to Core.
  CHANGELOG.md
  src/components/DpToggleForm/DpToggleForm.vue
  src/components/DpToggleForm/index.ts
  src/components/index.js
Labels: enhancement, review:frontend

#537 Add dp notify message to storybook
  CHANGELOG.md
  src/components/DpNotification/DpNotification.stories.mdx
  src/components/DpNotification/DpNotification.stories.tsx
  src/components/DpNotification/DpNotification.vue
  src/components/DpNotification/index.ts
  src/components/core/index.js
  src/components/core/notify/DpNotifyContainer.vue
  src/components/index.js
  tests/DpNotification.spec.js
  tests/__snapshots__/DpNotification.spec.js.snap
Labels: documentation, enhancement

#538 chore: WIP: Add DpModal to Storybook
  src/components/DpModal/DpModal.stories.mdx
  src/components/DpModal/DpModal.stories.tsx
  src/components/DpModal/DpModal.vue
Labels: documentation

#541 chore: add CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#544 chore: fix args error in DpTextArea.
  src/components/DpTextArea/DpTextArea.stories.tsx
Labels: bug, documentation

#545 chore: Fix DpTab Storybook error.
  src/components/DpTabs/DpTabs.stories.tsx
Labels: bug, documentation
