Repository demos-europe/demosplan-ui, pull requests merged in 2023-06, with the labels that each got.

#290 bug(refs T33153): Add missing props for multiselect
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
Labels: bug, review:frontend

#260 refactor(refs T30969): move components to components root, pt. III
  src/components/DpDataTable/DataTableSearch.js
  src/components/DpDataTable/DpColumnSelector.stories.mdx
  src/components/DpDataTable/DpColumnSelector.vue
  src/components/DpDataTable/DpDataTable.stories.mdx
  src/components/DpDataTable/DpDataTable.vue
  src/components/DpDataTable/DpDataTableExtended.stories.mdx
  src/components/DpDataTable/DpDataTableExtended.vue
  src/components/DpDataTable/DpResizableColumn.vue
  src/components/DpDataTable/DpResizeHandle.vue
  src/components/DpDataTable/DpSelectPageItemCount.vue
  src/components/DpDataTable/DpTableHeader.vue
  src/components/DpDataTable/DpTableRow.vue
  src/components/DpDataTable/DpWrapTrigger.vue
  src/components/DpStickyElement/DpStickyElement.vue
  src/components/DpTreeList/DpTreeList.vue
  src/components/DpTreeList/DpTreeListCheckbox.vue
  src/components/DpTreeList/DpTreeListNode.vue
  src/components/DpTreeList/DpTreeListToggle.vue
  src/components/DpTreeList/utils/bus.js
  src/components/DpTreeList/utils/constants.js
  src/components/core/DpSwitcher.vue
  src/components/core/DpTableCardList/DpTableCardListHeader.vue
  src/components/core/index.js
  src/components/index.js
Labels: enhancement, review:frontend

#256 refactor(refs T30969): remove DpCopyPasteButton
  CHANGELOG.md
  src/components/core/DpCopyPasteButton.vue
  src/components/core/index.js
  src/components/index.js
  src/index.js
Labels: enhancement, review:frontend, do-not-merge

#303 refactor(refs T30969): remove DpChangeStateAtDate
  CHANGELOG.md
  src/components/core/DpChangeStateAtDate.stories.mdx
  src/components/core/DpChangeStateAtDate.vue
  src/components/core/index.js
  src/components/index.js
  src/index.js
Labels: enhancement, review:frontend

#268 test: Add some Vue tests and a setup for them
  CHANGELOG.md
  jest.config.js
  jest/setup.js
  jest/shallowMountWithGlobalMocks.js
  package.json
  tests/DataTableSearch.spec.js
  tests/DpContextualHelp.spec.js
  tests/DpLabel.spec.js
  tests/DpNotifyMessage.spec.js
  tests/DpTreeListCheckbox.spec.js
  tests/DpUpload/DpUploadFiles.spec.js
  tests/Modal.spec.js
  tests/Obscure.spec.js
  tests/Tiptap/__snapshots__/handleWordPaste.spec.js.snap
  tests/Tiptap/handleWordPaste.spec.js
  tests/__mocks__/wordContentSnippets.mock.js
  tests/form/DpCheckbox.spec.js
  tests/form/DpInput.spec.js
  tests/form/DpSelect.spec.js
  tests/form/shared/Attributes.js
  tests/form/shared/Label.js
  tests/prefixClass.spec.js
  tests/utils/date.test.js
  tests/utils/debounce.test.js
  tests/utils/deepMerge.test.js
  tests/utils/formatBytes.test.js
  tests/utils/hasOwnProp.test.js
  tests/utils/hasPermission.test.js
  tests/utils/sortAlphabetically.test.js
  tests/utils/uniqueArrayByObjectKey.test.js
  yarn.lock
Labels: enhancement, review:frontend

#305 feat(refs T30976): add dp-autocomplete to storybook
  src/components/DpAutocomplete/DpAutocomplete.stories.mdx
Labels: review:frontend

#319 bug(refs T33411): Add prop for data-cy on its own
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
Labels: bug, review:frontend

#325 chore (refs T30980): remove some component class, to pass it from out…
  src/components/core/DpAnonymizeText.vue
Labels: enhancement, review:frontend

#326 chore (refs T30980): add changelog.
  CHANGELOG.md
Labels: enhancement, review:frontend

#327 chore (refs T30980): remove class, to pass it from outside.
  CHANGELOG.md
  src/components/DpFormRow/DpFormRow.vue
Labels: enhancement, review:frontend

#334 chore (refs T30980): remove spacing & layout classes.
  CHANGELOG.md
  src/components/core/DpBulkEditHeader.vue
Labels: enhancement, review:frontend

#335 chore (refs T30980): remove spacing class.
  CHANGELOG.md
  src/components/DpDataTable/DpDataTableExtended.vue
Labels: enhancement, review:frontend

#314 chore: Use Barrel Export to simplify index.js
  src/index.js
Labels: enhancement, review:frontend
