Repository demos-europe/demosplan-ui, pull requests merged in 2023-01, with the labels that each got.

#52 Add bundle analyzer
  package.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#56 Fix: Set a condition if the root element is empty WIP
  src/components/core/DpModal.vue
Labels: bug, frontend

#55 fix(refs T30430): Add tiptap to externals
  webpack.config.js
  yarn.lock
Labels: bug, frontend

#61 Transpile tiptap esm modules
  CHANGELOG.md
  webpack.config.js
Labels: bug

#66 fix(refs T31010): Don't use Translator directly in template
  src/components/core/DpEditor/DpResizableImage.vue
Labels: bug, enhancement, frontend

#73 bug(refs T27479): fix bulk edit for documents
  CHANGELOG.md
  src/components/core/DpTreeList/DpTreeList.vue
  src/components/core/DpTreeList/DpTreeListNode.vue
  src/components/core/DpTreeList/utils/bus.js
Labels: bug, frontend

#81 Fix paths after failed merge
  src/components/DpDateRangePicker/DpDateRangePicker.vue
  src/components/DpRadio/DpRadio.vue
  src/components/DpSearchField/DpSearchField.vue
  src/components/DpSelect/DpSelect.vue
  src/components/DpSlidingPagination/DpSlidingPagination.vue
  src/components/DpTimePicker/DpTimePicker.vue
  src/lib/ActionMenu.js
  src/lib/validation/utils/assignHandlerForTrigger.js
  src/mixins/prefixClassMixin/prefixClassMixin.js
Labels: bug

#53 feat(refs T21119): Add a wrapper for draggable
  src/components/core/DpDataTable/DpDataTable.vue
  src/components/core/DpDraggable.vue
  src/components/core/DpTreeList/DpTreeList.vue
  src/components/core/DpTreeList/DpTreeListNode.vue
  src/components/core/index.js
  src/components/index.js
  src/index.js
Labels: enhancement, frontend

#79 F t30977 no more permission queries in demosplan UI
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/libs/editorObscure.js
  src/components/core/DpObscure.vue
Labels: enhancement, frontend
