Repository demos-europe/demosplan-ui, pull requests merged in 2023-11, with the labels that each got.

#615 F t34968 add dp bulk edit header to storybook
  CHANGELOG.md
  src/components/core/DpBulkEditHeader.stories.mdx
  src/components/core/DpBulkEditHeader.stories.tsx
  src/components/core/DpBulkEditHeader.vue
  src/components/shared/translations.js
Labels: documentation

#627 chore: Fix DpTreeListCheckbox Test.
  tests/DpTreeListCheckbox.spec.js
Labels: bug, enhancement

#624 fix: Use proper import for buildSuggestion
  CHANGELOG.md
  src/components/core/DpEditor/libs/customExtensions.js
Labels: bug, review:frontend

#630 bug(refs T34956): Fix stickier position
  CHANGELOG.md
  src/lib/Stickier.js
Labels: bug

#628 F t34965 add methods für dp editable storybook
  src/components/core/DpEditableList.stories.tsx
Labels: documentation, enhancement

#648 bug: Align text for accordion button left
  src/components/DpAccordion/DpAccordion.vue
Labels: bug, review:frontend

#643 fix(refs T19759): fix warnings/errors [vue 3 upgrade]
  src/components/DpButton/DpButton.vue
  src/components/DpButtonRow/DpButtonRow.vue
  src/components/DpCheckbox/DpCheckbox.vue
  src/components/DpDataTable/DpTableHeader.vue
  src/components/DpDataTable/DpTableRow.vue
  src/components/DpDataTableExtended/DpDataTableExtended.vue
  src/components/DpInput/DpInput.vue
  src/components/DpSelect/DpSelect.vue
  src/components/DpTabs/DpTabs.vue
  src/components/DpTextArea/DpTextArea.vue
  src/components/DpTooltip/DpTooltip.vue
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/MentionList.vue
  src/components/core/DpUpload/DpUpload.vue
  src/components/core/DpUpload/DpUploadFiles.vue
  src/directives/CleanHtml/CleanHtml.js
  src/directives/Tooltip/Tooltip.js
  src/lib/validation/dpValidateMultiselectDirective.js
Labels: review:frontend
