Repository demos-europe/demosplan-ui, pull requests merged in 2023-05, with the labels that each got.

#195 chore(refs T19787, T19759): Rebuild template for selectPageItemCount
  src/components/core/DpDataTable/DpSelectPageItemCount.vue
Labels: enhancement, frontend

#201 Fix(refs T19787, T19759): Pass propper Prop
  CHANGELOG.md
  src/components/core/DpDataTable/DpDataTableExtended.vue
Labels: bug, review:frontend

#203 chore(refs T19787, T19759): Rebuild template for DpContextualHelp
  CHANGELOG.md
  src/components/DpContextualHelp/DpContextualHelp.vue
Labels: enhancement, review:frontend

#193 chore (refs T30974): Add (boxShadow & rounded) json to tokens.
  buildTokens.js
  tokens/boxShadow.json
  tokens/fontSize.json
  tokens/rounded.json
  tokens/tokens.box.shadow.stories.mdx
  tokens/tokens.font.size.stories.mdx
  tokens/tokens.rounded.stories.mdx
Labels: enhancement, review:frontend, do-not-merge

#108 Add missing color design tokens
  CHANGELOG.md
  buildTokens.js
  src/components/core/DpBulkEditHeader.vue
  src/components/core/DpDataTable/DpDataTableExtended.vue
  src/components/core/DpTabs/DpTabs.vue
  src/components/core/notify/DpNotifyMessage.vue
  src/utils/lengthHint/lengthHint.js
  tokens/_.json
  tokens/boxShadow.json
  tokens/color.stories.mdx
  tokens/color/color.brand.json
  tokens/color/color.data.json
  tokens/color/color.palette.json
  tokens/color/color.ui.json
  tokens/fontSize.json
  tokens/rounded.json
  tokens/tokens._overview.stories.mdx
  tokens/tokens.box.shadow.stories.mdx
  tokens/tokens.color.stories.mdx
  tokens/tokens.font.size.stories.mdx
  tokens/tokens.rounded.stories.mdx
Labels: enhancement, review:frontend, do-not-merge

#205 Feat: Convert DpTableHeader.vue to a template
  CHANGELOG.md
  src/components/core/DpDataTable/DpDataTable.vue
  src/components/core/DpDataTable/DpResizableColumn.vue
  src/components/core/DpDataTable/DpTableHeader.vue
  src/components/core/DpDataTable/lib/ResizableColumns.js
Labels: enhancement, review:frontend

#51 Feat: Configuration for tests in demosplan-ui
  CHANGELOG.md
  babel-jest-transformer.js
  babel.config.js
  jest.config.js
  package.json
  src/tests/utils/debounce.test.js
  src/tests/utils/formatBytes.test.js
  yarn.lock
Labels: enhancement, review:frontend

#234 bug(refs T32834): multiselect
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
  src/components/DpPager/DpPager.vue
Labels: bug, review:frontend

#237 bug(refs T3285): Fix multiselect
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
Labels: bug, review:frontend

#249 fix(refs: T32865): checkbox at wrong position and console errors
  .gitignore
  CHANGELOG.md
  src/components/core/DpDataTable/DpTableHeader.vue
Labels: review:frontend

#255 refactor(refs T30969): remove DpRegisterFlyout
  CHANGELOG.md
  src/components/core/DpRegisterFlyout.vue
  src/components/core/index.js
  src/components/index.js
  src/index.js
Labels: enhancement, review:frontend

#248 refactor(refs T30969): move components
  src/components/DpAutocomplete/DpAutocomplete.vue
  src/components/DpButtonIcon/DpButtonIcon.vue
  src/components/DpCard/DpCard.vue
  src/components/DpDraggable/DpDraggable.vue
  src/components/DpHeightLimit/DpHeightLimit.stories.mdx
  src/components/DpHeightLimit/DpHeightLimit.vue
  src/components/DpModal/DpModal.vue
  src/components/DpMultistepNav/DpMultistepNav.stories.mdx
  src/components/DpMultistepNav/DpMultistepNav.vue
  src/components/DpSkeletonBox/DpSkeletonBox.vue
  src/components/DpSlidebar/DpSlidebar.stories.mdx
  src/components/DpSlidebar/DpSlidebar.vue
  src/components/DpTabs/DpTab.vue
  src/components/DpTabs/DpTabs.vue
  src/components/DpToggleForm/DpToggleForm.vue
  src/components/DpTooltipIcon/DpTooltipIcon.stories.mdx
  src/components/DpTooltipIcon/DpTooltipIcon.vue
  src/components/core/DpDashboardTaskCard.vue
  src/components/core/DpDataTable/DpDataTable.vue
  src/components/core/DpEditor/DpLinkModal.vue
  src/components/core/DpEditor/DpRecommendationModal.vue
  src/components/core/DpEditor/DpUploadModal.vue
  src/components/core/DpTreeList/DpTreeList.vue
  src/components/core/DpTreeList/DpTreeListNode.vue
  src/components/core/index.js
  src/components/index.js
  src/index.js
Labels: enhancement, review:frontend

#259 T21517 Add subtle button variant
  CHANGELOG.md
  src/components/DpButton/DpButton.stories.mdx
  src/components/DpButton/DpButton.vue
  src/components/DpIcon/DpIcon.stories.mdx
  src/components/DpIcon/util/iconVariables.js
  tokens/color/color.ui.json
Labels: do-not-merge
