Repository demos-europe/demosplan-ui, pull requests merged in 2023-10, with the labels that each got.

#556 Add dp tree list to storybook
  CHANGELOG.md
  src/components/DpTreeList/DpTreeList.stories.mdx
  src/components/DpTreeList/DpTreeList.stories.tsx
  src/components/DpTreeList/DpTreeListCheckbox.vue
  src/components/DpTreeList/DpTreeListToggle.vue
  src/components/shared/translations.js
Labels: documentation, do-not-merge

#557 chore: backmerge release_ewm to main
  CHANGELOG.md
  package.json
  src/components/DpTooltip/utils/tooltip.js
  src/directives/Tooltip/Tooltip.js
  tests/DpContextualHelp.spec.js
  tests/__snapshots__/DpContextualHelp.spec.js.snap
Labels: review:frontend

#558 fix: Adjust Test after Refactoring
  package.json
  tests/DpTreeListCheckbox.spec.js
  yarn.lock
Labels: bug, review:frontend

#567 chore (refs T34979): add DpEditor to Storybook.
  CHANGELOG.md
  src/components/core/DpEditor/DpEditor.stories.mdx
  src/components/core/DpEditor/DpEditor.stories.tsx
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/DpUploadModal.vue
Labels: documentation

#586 fix(refs T34963): Add existing Attrs to Link Node
  CHANGELOG.md
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/libs/editorCustomLink.js
Labels: bug, review:frontend

#592 feat: group tiptap and storybook dependabot PRs
  .github/dependabot.yml
Labels: enhancement, dependencies

#591 refactor(refs T29004): re-add label tests
  CHANGELOG.md
  tests/form/DpCheckbox.spec.js
  tests/form/DpInput.spec.js
  tests/form/DpSelect.spec.js
  tests/form/shared/Label.js
Labels: review:frontend

#605 F t34965 add dp editable list to storybook
  CHANGELOG.md
  src/components/DpButtonRow/DpButtonRow.vue
  src/components/DpDataTable/DpDataTable.vue
  src/components/DpMultiselect/DpMultiselect.vue
  src/components/DpTreeList/DpTreeListCheckbox.vue
  src/components/core/DpEditableList.stories.mdx
  src/components/core/DpEditableList.stories.tsx
  src/components/core/DpEditableList.vue
  src/components/shared/translations.js
  tests/form/DpSelect.spec.js
Labels: documentation

#603 chore: remove some component from ui, move it to Core.
  CHANGELOG.md
  src/components/DpHeightLimit/DpHeightLimit.stories.mdx
  src/components/DpHeightLimit/DpHeightLimit.stories.tsx
  src/components/DpHeightLimit/DpHeightLimit.vue
  src/components/DpHeightLimit/index.ts
  src/components/core/DpSwitcher.stories.mdx
  src/components/core/DpSwitcher.stories.tsx
  src/components/core/DpSwitcher.vue
  src/components/core/DpTextWrapper.vue
  src/components/core/index.js
  src/components/index.js
Labels: review:frontend
