Repository demos-europe/demosplan-ui, pull requests merged in 2023-07, with the labels that each got.

#344 chore (refs T33323): add storybook documentation to DpTabs.
  CHANGELOG.md
  src/components/DpTabs/DpTabs.stories.mdx
Labels: documentation

#357 F t31115 remove translator from dp select
  CHANGELOG.md
  src/components/DpSelect/DpSelect.vue
  src/components/shared/translations.js
Labels: enhancement, review:frontend

#350 chore (refs T33323): add storybook for DpSelect component.
  src/components/DpSelect/DpSelect.stories.mdx
  src/components/DpSelect/DpSelect.vue
Labels: documentation, do-not-merge

#363 Fix: Add a default export to index.js
  src/index.js
Labels: bug, review:frontend

#361 Tweak Tailwind config with utility tokens
  CHANGELOG.md
  buildTokens.js
  package.json
  tailwind.config.js
  tokens/rounded.json
  tokens/src/_.json
  tokens/src/boxShadow.json
  tokens/src/breakpoints.json
  tokens/src/color/color.brand.json
  tokens/src/color/color.data.json
  tokens/src/color/color.palette.json
  tokens/src/color/color.ui.json
  tokens/src/fontSize.json
  tokens/src/rounded.json
  tokens/src/space.json
  tokens/src/zIndex.json
  tokens/tokens.boxShadow.stories.mdx
  tokens/tokens.breakpoints.stories.mdx
  tokens/tokens.fontSize.stories.mdx
  tokens/tokens.zIndex.stories.mdx
  yarn.lock
Labels: documentation, enhancement

#365 documentation: Add missing Changelog entry for barrel export
  CHANGELOG.md
Labels: documentation, review:frontend

#370 chore (refs T33316): add DpRadio to storybook.
  CHANGELOG.md
  src/components/DpRadio/DpRadio.stories.mdx
Labels: documentation, review:frontend

#336 refactor(refs T33194, T19759): Migrate tiptap to v2 - init
  package.json
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/libs/customExtensions.js
  src/components/core/DpEditor/libs/tiptapExtensions.js
Labels: enhancement, review:frontend

#291 chore(refs T30981) Typescript support demosplan UI
  CHANGELOG.md
  package.json
  src/components/DpButton/DpButton.vue
  src/components/DpRadio/DpRadio.vue
  tsconfig.json
  vue-shims.d.ts
  webpack.config.js
  yarn.lock
Labels: enhancement, review:frontend

#337 refactor(refs T33194, T19759): Add mentions/suggestions to tiptap@V2
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/MentionList.vue
  src/components/core/DpEditor/libs/CustomMention.js
  src/components/core/DpEditor/libs/editorBuildSuggestion.js
Labels: enhancement, review:frontend

#340 refactor(refs T33194, T19759): Add Custom Del/Mark/inserted to tiptap@V2
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/libs/editorCustomDelete.js
  src/components/core/DpEditor/libs/editorCustomInsert.js
  src/components/core/DpEditor/libs/editorCustomMark.js
Labels: enhancement, review:frontend

#341 refactor(refs T33194, T19759): Add Obscure and insertAtCursorPos
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/libs/editorInsertAtCursorPos.js
  src/components/core/DpEditor/libs/editorObscure.js
Labels: enhancement, review:frontend

#395 F upgrade storybook migrate dp flayout
  .storybook/main.js
  src/components/DpAccordion/DpAccordion.stories.mdx
  src/components/DpAccordion/DpAccordion.stories.tsx
  src/components/DpContextualHelp/DpContextualHelp.stories.mdx
  src/components/DpContextualHelp/DpContextualHelp.stories.tsx
  src/components/DpFlyout/DpFlyout.stories.mdx
  src/components/DpFlyout/DpFlyout.stories.tsx
  src/components/DpHeightLimit/DpHeightLimit.mdx
  src/components/DpHeightLimit/DpHeightLimit.stories.mdx
  src/components/DpHeightLimit/DpHeightLimit.stories.tsx
  tokens/tokens._overview.stories.mdx
  tokens/tokens.boxShadow.stories.mdx
  tokens/tokens.breakpoints.stories.mdx
  tokens/tokens.color.stories.mdx
  tokens/tokens.fontSize.stories.mdx
  tokens/tokens.rounded.stories.mdx
  tokens/tokens.zIndex.stories.mdx
Labels: documentation

#396 F upgrade storybook migrate dp autocomplete
  src/components/DpAccordion/DpAccordion.stories.mdx
  src/components/DpAccordion/DpAccordion.stories.tsx
  src/components/DpAutocomplete/DpAutocomplete.stories.mdx
  src/components/DpAutocomplete/DpAutocomplete.stories.tsx
  src/components/DpAutocomplete/DpAutocomplete.vue
  src/components/DpContextualHelp/DpContextualHelp.stories.mdx
  src/components/DpContextualHelp/DpContextualHelp.stories.tsx
  src/components/DpFlyout/DpFlyout.stories.mdx
  src/components/DpFlyout/DpFlyout.stories.tsx
  src/components/DpHeightLimit/DpHeightLimit.stories.mdx
  src/components/DpHeightLimit/DpHeightLimit.stories.tsx
  src/components/shared/translations.js
Labels: documentation, enhancement, review:frontend

#397 F upgrade storybook migrate dp button
  src/components/DpButton/DpButton.stories.mdx
  src/components/DpButton/DpButton.stories.tsx
Labels: documentation
