Repository demos-europe/demosplan-ui, pull requests merged in 2023-08, with the labels that each got.

#399 chore: Migrate DpCheckbox stories to v7.
  src/components/DpCheckbox/DpCheckbox.stories.mdx
  src/components/DpCheckbox/DpCheckbox.stories.tsx
Labels: documentation

#401 F upgrade storybook migrate dp icon
  src/components/DpIcon/DpIcon.stories.mdx
  src/components/DpIcon/DpIcon.stories.tsx
Labels: documentation

#400 chore: Migrate DpDetails stories to v7.
  src/components/DpDetails/DpDetails.stories.mdx
  src/components/DpDetails/DpDetails.stories.tsx
Labels: documentation

#406 F upgrade storybook migrate dp input
  src/components/DpInput/DpInput.stories.mdx
  src/components/DpInput/DpInput.stories.tsx
Labels: documentation

#407 F upgrade storybook migrate dp label
  src/components/DpLabel/DpLabel.stories.mdx
  src/components/DpLabel/DpLabel.stories.tsx
Labels: documentation

#410 F upgrade storybook migrate dp loading
  src/components/DpLoading/DpLoading.stories.mdx
  src/components/DpLoading/DpLoading.stories.tsx
Labels: documentation

#398 F upgrade storybook migrate dp button row
  src/components/DpButtonRow/DpButtonRow.stories.mdx
  src/components/DpButtonRow/DpButtonRow.stories.tsx
  src/components/DpButtonRow/DpButtonRow.vue
  src/components/shared/translations.js
Labels: documentation

#412 chore: fix Validate directive in DpMultiselect.
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
Labels: enhancement, review:frontend

#408 F upgrade storybook migrate dp multiselect
  src/components/DpMultiselect/DpMultiselect.stories.mdx
  src/components/DpMultiselect/DpMultiselect.stories.tsx
  src/components/DpMultiselect/DpMultiselect.vue
  src/components/shared/translations.js
Labels: documentation

#411 chore: Migrate DpMultistepNav story to v7.
  src/components/DpMultistepNav/DpMultistepNav.stories.mdx
  src/components/DpMultistepNav/DpMultistepNav.stories.tsx
Labels: documentation

#418 F upgrade storybook migrate dp select
  src/components/DpSelect/DpSelect.stories.mdx
  src/components/DpSelect/DpSelect.stories.tsx
Labels: documentation

#416 F upgrade storybook migrate dp radio
  src/components/DpRadio/DpRadio.stories.mdx
  src/components/DpRadio/DpRadio.stories.tsx
Labels: documentation

#419 F upgrade storybook migrate dp tabs
  src/components/DpTabs/DpTabs.stories.mdx
  src/components/DpTabs/DpTabs.stories.tsx
Labels: documentation

#384 F upgrade storybook move data structure
  src/components/DpHeightLimit/DpHeightLimit.stories.tsx
  src/components/DpSlidebar/DpSlidebar.stories.mdx
  src/components/DpSlidebar/DpSlidebar.stories.tsx
Labels: documentation, do-not-merge

#429 chore: Migrate DpDataTable stories to v7.
  src/components/DpDataTable/DpDataTable.stories.mdx
  src/components/DpDataTable/DpDataTable.stories.tsx
  src/components/DpDataTable/DpDataTable.vue
  src/components/shared/translations.js
Labels: documentation

#437 chore (refs T33945): add missing Hooks/Selectors.
  CHANGELOG.md
  src/components/DpSplitButton/DpSplitButton.vue
Labels: enhancement, review:frontend

#443 chore (refs T34082): add E2E Props.
  CHANGELOG.md
  src/components/DpDateRangePicker/DpDateRangePicker.vue
  src/components/DpDatepicker/DpDatepicker.vue
Labels: enhancement, review:frontend

#438 Fix(T34173): flickering text when scrolling down
  CHANGELOG.md
  src/components/DpTreeList/DpTreeList.vue
  src/lib/Stickier.js
Labels: review:frontend

#444 chore (refs T34037): add E2E Prop.
  CHANGELOG.md
  src/components/DpAccordion/DpAccordion.vue
Labels: enhancement, review:frontend

#420 refactor(refs T31187): remove Translator usages
  src/components/DpContextualHelp/DpContextualHelp.vue
  src/components/DpDataTable/DpColumnSelector.vue
  src/components/DpDataTable/DpDataTable.vue
  src/components/DpLabel/DpLabel.vue
  src/components/DpModal/DpModal.vue
  src/components/DpMultiselect/DpMultiselect.vue
  src/components/DpSelect/DpSelect.vue
  src/components/DpTreeList/DpTreeListCheckbox.vue
  src/components/core/DpAnonymizeText.vue
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/DpLinkModal.vue
  src/components/core/DpEditor/DpResizableImage.vue
  src/components/core/DpEditor/DpUploadModal.vue
  src/components/core/DpEditor/libs/editorCustomDelete.js
  src/components/core/DpEditor/libs/editorCustomInsert.js
  src/components/core/DpEditor/libs/editorCustomMark.js
  src/components/core/DpObscure.vue
  src/components/core/DpUpload/DpUploadedFile.vue
  src/components/core/DpUpload/utils/UppyTranslations.js
  src/components/shared/translations.js
  src/lib/validation/utils/validateInputField.js
  src/mixins/dpValidateMixin.js
  src/utils/lengthHint/lengthHint.js
  tests/DpTreeListCheckbox.spec.js
  tests/Obscure.spec.js
  tests/__snapshots__/DpContextualHelp.spec.js.snap
Labels: enhancement, review:frontend

#445 refactor(refs T31187): remove DpDashboardTaskCard
  CHANGELOG.md
  src/components/core/DpDashboardTaskCard.vue
  src/components/core/index.js
  src/components/index.js
Labels: enhancement, review:frontend

#453 refactor(refs T31187): move changelog entry
  CHANGELOG.md
Labels: review:frontend

#383 feat: Add new DpTooltip and refactor v-tooltip Directive
  .storybook/preview.js
  CHANGELOG.md
  package.json
  src/components/DpTooltip/DpTooltip.stories.mdx
  src/components/DpTooltip/DpTooltip.vue
  src/components/DpTooltip/utils/tooltip.js
  src/components/index.js
  src/directives/Tooltip/Tooltip.js
  yarn.lock
Labels: enhancement, review:frontend

#454 F upgrade storybook migrate dp toggle
  src/components/DpToggle/DpToggle.mdx
  src/components/DpToggle/DpToggle.stories.mdx
  src/components/DpToggle/DpToggle.stories.tsx
  src/components/shared/translations.js
Labels: documentation

#459 chore: Migrate DpPager stories to v7.
  src/components/DpPager/DpPager.stories.mdx
  src/components/DpPager/DpPager.stories.tsx
Labels: documentation

#463 chore: Migrate DpTooltipIcon stories to v7.
  src/components/DpTooltipIcon/DpTooltipIcon.stories.mdx
  src/components/DpTooltipIcon/DpTooltipIcon.stories.tsx
Labels: documentation

#461 chore: Migrate DpResettableInput stories to v7.
  src/components/DpResettableInput/DpResettableInput.stories.mdx
  src/components/DpResettableInput/DpResettableInput.stories.tsx
Labels: documentation

#430 F upgrade storybook migrate dp data table extended
  src/components/DpDataTable/DpDataTableExtended.stories.mdx
Labels: documentation

#465 chore: WIP: Migrate DpEditor stories to v7.
  src/components/core/DpEditor/DpEditor.stories.mdx
  src/components/core/DpEditor/DpEditor.vue
  src/components/shared/translations.js
Labels: documentation

#472 chore: migrate DpCard to Storybook 7.
  CHANGELOG.md
  src/components/DpCard/DpCard.stories.mdx
  src/components/DpCard/DpCard.stories.tsx
Labels: documentation

#477 chore: Add DpCheckboxGroup to Storybook.
  CHANGELOG.md
  src/components/DpCheckboxGroup/DpCheckboxGroup.stories.mdx
  src/components/DpCheckboxGroup/DpCheckboxGroup.stories.tsx
Labels: documentation

#476 fix: Clear Bugs after merging all together
  package.json
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/libs/editorCustomLink.js
  src/components/core/DpEditor/libs/editorCustomMark.js
  src/lib/index.js
  webpack.config.js
  yarn.lock
Labels: enhancement, review:frontend

#479 chore: add DpInlineNotification to Storybook.
  CHANGELOG.md
  src/components/DpInlineNotification/DpInlineNotification.stories.mdx
  src/components/DpInlineNotification/DpInlineNotification.stories.tsx
Labels: documentation

#473 F t32983 move generic components to demosplan UI
  CHANGELOG.md
  src/components/DpBadge/DpBadge.stories.mdx
  src/components/DpBadge/DpBadge.stories.tsx
  src/components/DpBadge/DpBadge.vue
  src/components/index.js
Labels: review:frontend

#480 chore: add DpSkeletonBox to Storybook.
  CHANGELOG.md
  src/components/DpSkeletonBox/DpSkeletonBox.stories.mdx
  src/components/DpSkeletonBox/DpSkeletonBox.stories.tsx
Labels: documentation

#483 fix: Adjust storybook
  package.json
  src/components/DpAccordion/DpAccordion.stories.tsx
  src/components/DpAutocomplete/DpAutocomplete.stories.tsx
  src/components/DpButton/DpButton.stories.tsx
  src/components/DpButtonRow/DpButtonRow.stories.tsx
  src/components/DpCard/DpCard.stories.tsx
  src/components/DpCheckbox/DpCheckbox.stories.tsx
  src/components/DpCheckboxGroup/DpCheckboxGroup.stories.tsx
  src/components/DpContextualHelp/DpContextualHelp.stories.tsx
  src/components/DpDataTable/DpColumnSelector.stories.tsx
  src/components/DpDataTable/DpDataTable.stories.tsx
  src/components/DpDetails/DpDetails.stories.tsx
  src/components/DpFlyout/DpFlyout.stories.tsx
  src/components/DpHeightLimit/DpHeightLimit.stories.tsx
  src/components/DpIcon/DpIcon.stories.tsx
  src/components/DpInlineNotification/DpInlineNotification.stories.tsx
  src/components/DpInput/DpInput.stories.tsx
  src/components/DpLabel/DpLabel.stories.tsx
  src/components/DpLoading/DpLoading.stories.tsx
  src/components/DpMultiselect/DpMultiselect.stories.tsx
  src/components/DpMultistepNav/DpMultistepNav.stories.tsx
  src/components/DpPager/DpPager.stories.tsx
  src/components/DpRadio/DpRadio.stories.tsx
  src/components/DpResettableInput/DpResettableInput.stories.tsx
  src/components/DpSelect/DpSelect.stories.tsx
  src/components/DpSlidebar/DpSlidebar.stories.tsx
  src/components/DpTabs/DpTabs.stories.tsx
  src/components/DpToggle/DpToggle.stories.tsx
  src/components/DpTooltipIcon/DpTooltipIcon.stories.tsx
  yarn.lock
Labels: bug

#481 chore: add DpSplitButton to Storybook.
  CHANGELOG.md
  src/components/DpSplitButton/DpSplitButton.stories.mdx
  src/components/DpSplitButton/DpSplitButton.stories.tsx
Labels: documentation

#488 fix: fix Storybook errors.
  src/components/DpAccordion/DpAccordion.stories.tsx
  src/components/DpBadge/DpBadge.stories.tsx
  src/components/DpSelect/DpSelect.stories.mdx
Labels: bug, documentation

#374 refactor(refs T33194, T19759): Migrate tiptap to v2 - Integration
  package.json
  src/components/core/DpAnonymizeText.vue
  src/components/core/DpEditor/DpEditor.vue
  src/components/core/DpEditor/DpResizableImage.vue
  src/components/core/DpEditor/MentionList.vue
  src/components/core/DpEditor/libs/customExtensions.js
  src/components/core/DpEditor/libs/editorAnonymize.js
  src/components/core/DpEditor/libs/editorBuildSuggestion.js
  src/components/core/DpEditor/libs/editorCustomDelete.js
  src/components/core/DpEditor/libs/editorCustomImage.js
  src/components/core/DpEditor/libs/editorCustomInsert.js
  src/components/core/DpEditor/libs/editorCustomLink.js
  src/components/core/DpEditor/libs/editorCustomMark.js
  src/components/core/DpEditor/libs/editorInsertAtCursorPos.js
  src/components/core/DpEditor/libs/editorMention.js
  src/components/core/DpEditor/libs/editorObscure.js
  src/components/core/DpEditor/libs/editorUnAnonymize.js
  src/components/core/DpEditor/libs/preventDrop.js
  src/components/core/DpEditor/libs/preventEditing.js
  src/components/core/DpEditor/libs/preventKeyboardInput.js
  src/components/core/DpEditor/libs/preventPaste.js
  src/components/core/DpEditor/libs/tiptapExtensions.js
  src/lib/index.js
  webpack.config.js
  yarn.lock
Labels: enhancement

#498 fix: fix storybook errors, update version.
  package.json
  yarn.lock
Labels: bug
