Repository demos-europe/demosplan-ui, pull requests merged in 2024-10, with the labels that each got.

#994 chore: Migrate from yarn1.22.22 to yarn4.2.2
  CHANGELOG.md
  package.json
  webpack.config.js
  yarn.lock
Labels: enhancement, review:frontend

#1032 Chore remove max chunk size on uploads vue2 version
  CHANGELOG.md
  src/components/DpUploadFiles/DpUpload.vue
Labels: bug, review:frontend

#968 doc: adjust changelog
  CHANGELOG.md
Labels: documentation

#1023 build(refs T19759): use vueuse/useSortable instead of vuedraggable [vue 3 upgrade] #682
  CHANGELOG.md
  package.json
  src/components/DpButton/DpButton.vue
  src/components/DpContextualHelp/DpContextualHelp.vue
  src/components/DpDataTable/DpDataTable.vue
  src/components/DpDataTable/DpTableHeader.vue
  src/components/DpDraggable/DpDraggable.vue
  src/components/DpEditor/libs/Decoration.js
  src/components/DpEditor/libs/SegmentRangeChangePlugin.js
  src/components/DpEditor/libs/editorInsertAtCursorPos.js
  src/components/DpTransitionExpand/DpTransitionExpand.vue
  src/components/DpTreeList/DpTreeList.vue
  src/components/DpTreeList/DpTreeListNode.vue
  src/lib/validation/utils/validateInputField.js
  yarn.lock
Labels: enhancement

#1042 fix(refs DPLAN-12516): restore closeButton slot
  CHANGELOG.md
  src/components/DpModal/DpModal.vue
Labels: review:frontend

#1043 fix(refs dplan-12602): Allow DpEditor to dismiss HTML from Word
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
  src/components/DpEditor/libs/handleWordPaste.js
  src/components/shared/translations.js
Labels: bug, enhancement

#1044 fix(refs dplan-12602): Allow DpEditor to dismiss HTML from Word (#1043)
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
  src/components/DpEditor/libs/handleWordPaste.js
  src/components/shared/translations.js
Labels: bug, review:frontend

#1052 fix(refs dplan-12315): Pass Item to dataTable instead of header-fields.
  CHANGELOG.md
  src/components/DpDataTable/DpDataTable.vue
  src/components/DpDataTableExtended/DpDataTableExtended.vue
Labels: bug

#1054 fix(refs dplan-12315): Make multiselect validation vue3 compatible
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
  src/lib/validation/dpValidateMultiselectDirective.js
Labels: bug

#1053 fix(refs dplan-12315): Configure Option to deny drag/dropping on rootlevel
  CHANGELOG.md
  src/components/DpToggle/DpToggle.vue
  src/components/DpTreeList/DpTreeList.vue
Labels: bug
