Repository demos-europe/demosplan-ui, pull requests merged in 2024-07, with the labels that each got.

#908 chore (refs DPLAN-3485): Add missing Hooks/Selectors.
  CHANGELOG.md
  src/components/DpDataTable/DpDataTable.vue
Labels: enhancement, review:frontend

#912 chore (refs DPLAN-11820): Add E-2-E Prop.
  CHANGELOG.md
  src/components/DpButtonRow/DpButtonRow.vue
Labels: enhancement, review:frontend

#916 chore (refs DPLAN-12005): add missing Hook.
  CHANGELOG.md
  src/components/DpBulkEditHeader/DpBulkEditHeader.vue
Labels: enhancement, review:frontend

#917 fix (refs DPLAN-1952): Fix cut methode for TipTap Editor.
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
Labels: bug, review:frontend, do-not-merge

#921 fix (refs DPLAN-12028, DPLAN-12029): Add missing Hooks Prop.
  CHANGELOG.md
  src/components/DpInlineNotification/DpInlineNotification.vue
Labels: enhancement, review:frontend

#925 Reduce package size
  .npmignore
  babel-jest-transformer.js
Labels: enhancement

#926 fix (refs DPLAN-12078): Add missing Hooks.
  CHANGELOG.md
  src/components/DpTreeList/DpTreeList.vue
  src/components/DpTreeList/DpTreeListNode.vue
Labels: enhancement, review:frontend

#940 chor (refs DPLAN-11885): Add Jest Test for the DpFlyout component.
  tests/DpFlyout.spec.js
Labels: enhancement, review:frontend

#938 F dplan 11885 upgrade jest test vue3
  tests/Obscure.spec.js
  tests/components/DpTreeList/DpTreeList.spec.js
  tests/components/DpTreeList/DpTreeListNode.spec.js
Labels: enhancement, review:frontend

#919 feat(refs DPLAN-11981): Add image to modal
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
  src/components/DpEditor/DpResizableImage.vue
  src/components/DpEditor/DpUploadModal.vue
Labels: enhancement, review:frontend

#929 chore (refs DPLAN-12089): add E-2-E Props.
  CHANGELOG.md
  src/components/DpUploadFiles/DpUpload.vue
  src/components/DpUploadFiles/DpUploadFiles.vue
Labels: enhancement, review:frontend

#955 fix(refs DPLAN-12137): Pass Data to tableHeader
  CHANGELOG.md
  src/components/DpDataTable/DpDataTable.vue
  src/components/DpDataTable/DpTableHeader.vue
Labels: bug

#961 bug (refs DPLAN-12159): Add class attribute to custom links
  CHANGELOG.md
  src/components/DpEditor/libs/editorCustomLink.js
Labels: bug, review:frontend
