Repository demos-europe/demosplan-ui, pull requests merged in 2024-05, with the labels that each got.

#844 fix(refs DPLAN-11529): Don't change Width from Next El on Datatable resize
  CHANGELOG.md
  src/components/DpDataTable/DpDataTable.vue
  src/components/DpDataTable/DpResizableColumn.vue
Labels: bug

#848 fix(refs DPLAN-1898): Destroy Tooltip instead of hiding
  CHANGELOG.md
  src/components/DpTooltip/utils/tooltip.js
Labels: bug, review:frontend

#860 bug (refs DPLAN-11472): Only setAttribute if datePickerInput is defined
  CHANGELOG.md
  src/components/DpDatepicker/DpDatepicker.vue
Labels: bug, review:frontend

#865 bug (refs DPLAN-11586): Remove header from form posts
  CHANGELOG.md
  src/lib/DpApi.js
Labels: bug, review:frontend

#859 chore (refs DPLAN-11426): Add missing Hooks/Selectors for uploaded fi…
  CHANGELOG.md
  src/components/DpUploadFiles/DpUploadedFile.vue
  src/components/DpUploadFiles/DpUploadedFileList.vue
Labels: enhancement, review:frontend

#868 chore (refs DPLAN-11504): Adjust data-cy Hooks/Selectors.
  CHANGELOG.md
  src/components/DpEditableList/DpEditableList.vue
Labels: enhancement, review:frontend

#879 feat(refs DPLAN-11601): Add translations as prop
  src/components/DpDataTableExtended/DpDataTableExtended.vue
Labels: enhancement, review:frontend

#881 chore (refs DPLAN-11668): Add missing Hooks for E-2-E Test.
  CHANGELOG.md
  src/components/DpMultistepNav/DpMultistepNav.vue
Labels: enhancement, review:frontend
