Repository demos-europe/demosplan-ui, pull requests merged in 2024-11, with the labels that each got.

#1068 feat(refs DPLAN-3217): allow disabling secondary button
  CHANGELOG.md
  src/components/DpButtonRow/DpButtonRow.vue
Labels: review:frontend

#1069 feat(refs DPLAN-3217): allow disabling secondary button
  CHANGELOG.md
  src/components/DpButtonRow/DpButtonRow.vue
Labels: review:frontend

#1067 fix: DpButton as Link and Input spacing
  CHANGELOG.md
  src/components/DpButton/DpButton.vue
  src/components/DpInput/DpInput.vue
  src/components/DpLabel/DpLabel.vue
  src/components/DpSelect/DpSelect.vue
  src/components/DpTextArea/DpTextArea.vue
Labels: bug, enhancement

#1074 feat (refs DPLAN-3217 AB#12115): Allow numbers as value for input
  CHANGELOG.md
  src/components/DpEditableList/DpEditableList.vue
  src/components/DpInput/DpInput.vue
Labels: enhancement, review:frontend

#1088 fix(refs DPLAN-12808): make sure 'sr-only' is applied if hide is true [vue 2]
  CHANGELOG.md
  src/components/DpLabel/DpLabel.vue
Labels: bug, review:frontend

#1085 fix(refs DPLAN-12746): allow passing options to v-tooltip [vue 3]
  CHANGELOG.md
  src/components/DpContextualHelp/DpContextualHelp.vue
Labels: review:frontend

#1087 fix(refs DPLAN-12823): Add 'reset' type to DpButton [vue 3]
  CHANGELOG.md
  src/components/DpButton/DpButton.vue
Labels: review:frontend

#1090 build: add .yarnrc.yml file
  .yarnrc.yml
  CHANGELOG.md
Labels: review:frontend

#1091 fix(refs DPLAN-12907): fix imports
  CHANGELOG.md
  src/components/DpEditor/DpUploadModal.vue
  src/components/DpUploadFiles/DpUploadFiles.stories.mdx
  tests/DpUpload/DpUploadFiles.spec.js
Labels: bug, review:frontend

#1094 fix(refs DPLAN-12886): fix overlapping flyout by adjusting css [VUE2]
  CHANGELOG.md
  src/components/DpDataTable/DpTableRow.vue
Labels: review:frontend

#1093 fix(refs DPLAN-12886): fix overlapping flyout by adjusting css [VUE3]
  CHANGELOG.md
  src/components/DpDataTable/DpTableRow.vue
Labels: review:frontend

#1099 feat(refs DPLAN-12914, #AB17874): adjust toggle alignment, display tooltips
  CHANGELOG.md
  src/components/DpTreeList/DpTreeList.vue
  src/components/DpTreeList/DpTreeListNode.vue
  src/components/DpTreeList/DpTreeListToggle.vue
  src/components/shared/translations.js
Labels: review:frontend

#1092 fix(refs DPLAN-12907): fix DpUploadFiles imports [vue 3]
  CHANGELOG.md
  src/components/DpEditor/DpUploadModal.vue
  src/components/DpUploadFiles/DpUploadFiles.stories.mdx
  tests/DpUpload/DpUploadFiles.spec.js
Labels: bug, review:frontend

#1101 fix(refs DPLAN-12460): addjust style to always display flyout properly
  src/components/DpDataTable/DpTableRow.vue
Labels: bug, review:frontend
