Repository demos-europe/demosplan-ui, pull requests merged in 2024-01, with the labels that each got.

#703 bug (refs T35953): Don't stringify form data
  CHANGELOG.md
  src/lib/DpApi.js
Labels: bug, review:frontend

#714 chore: send csrf token when submitting a rpc2.0 call
  CHANGELOG.md
  src/lib/DpApi.js
Labels: review:frontend

#718 chore (refs T34287): Add missing data attr for E-2-E Test.
  CHANGELOG.md
  src/components/DpColumnSelector/DpColumnSelector.vue
  src/components/DpFlyout/DpFlyout.vue
Labels: enhancement, review:frontend
