Repository demos-europe/demosplan-ui, pull requests merged in 2024-02, with the labels that each got.

#734 feat: allow mailto links in editor
  CHANGELOG.md
  src/components/DpEditor/DpLinkModal.vue
Labels: enhancement

#748 bug: Fix required for multiselect
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
Labels: bug, review:frontend

#739 chore (refs T34245): Add missing Hooks/Selectors.
  CHANGELOG.md
  src/components/DpEditableList/DpEditableList.vue
  src/components/DpSelect/DpSelect.vue
  src/components/DpTextArea/DpTextArea.vue
Labels: enhancement, review:frontend

#763 chore (refs T19759 T19784): migration render function to Vue3.
  src/components/DpTransitionExpand/DpTransitionExpand.vue
Labels: enhancement, review:frontend

#769 chore (refs T34245): Add missing Hooks/Selectors.
  src/components/DpButtonRow/DpButtonRow.vue
Labels: enhancement, review:frontend
