Repository demos-europe/demosplan-ui, pull requests merged in 2025-02, with the labels that each got.

#1156 feat(refs DPLAN-12968): introduce condensed search field [vue 3]
  CHANGELOG.md
  src/components/DpResettableInput/DpResettableInput.vue
  src/components/DpSearchField/DpSearchField.vue
  tests/DpSearchField.spec.js
Labels: review:frontend

#1167 b-DPLAN-12869: add idDisabled prop to dl-label to change cursor style
  CHANGELOG.md
  src/components/DpInput/DpInput.vue
  src/components/DpLabel/DpLabel.vue
Labels: review:frontend

#1172 b-DPLAN-14659: add keys to navigate to preventEditing.js
  CHANGELOG.md
  src/components/DpEditor/libs/preventEditing.js
Labels: bug, review:frontend

#1176 feat(refs DPLAN-14634, #AB22463): add dots-three icon [vue 3]
  CHANGELOG.md
  src/components/DpIcon/util/iconConfig.ts
  types/icons.ts
Labels: review:frontend

#1175 feat(refs DPLAN-14634, #AB22463): add dots-three icon
  CHANGELOG.md
  src/components/DpIcon/util/iconVariables.js
Labels: review:frontend

#1151 feat: add labelTexts props for improved dynamic labeling in DpPager
  CHANGELOG.md
  src/components/DpPager/DpPager.vue
  src/components/shared/translations.js
Labels: review:frontend

#1185 B dplan 12502 wrong icon alignment
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
Labels: review:frontend

#1188 feat(refs DPLAN-14634, #AB22463): add faders icon
  CHANGELOG.md
  src/components/DpIcon/util/iconVariables.js
Labels: review:frontend

#1187 feat(refs DPLAN-14634): add ariaLabel prop to DpFlyout
  CHANGELOG.md
  src/components/DpFlyout/DpFlyout.vue
Labels: review:frontend

#1184 B dplan 12918 no spacing when DbButtonRow wraps
  CHANGELOG.md
  src/components/DpButtonRow/DpButtonRow.vue
Labels: review:frontend

#1192 bug(refs DPLAN-14980): Use dynamic time pattern
  CHANGELOG.md
  src/components/DpTimePicker/DpTimePicker.vue
Labels: bug

#1198 chore: Implement Changes done in 0.3.x
  CHANGELOG.md
  src/components/DpDataTable/DpTableRow.vue
  src/components/DpFlyout/DpFlyout.vue
Labels: bug
