Repository demos-europe/demosplan-ui, pull requests merged in 2025-08, with the labels that each got.

#1330 feat(refs DPLAN-14969, #AB23560): Allow non-error DpNotification MSGs to persist
  CHANGELOG.md
  src/components/DpNotification/DpNotification.vue
Labels: enhancement, review:frontend

#1328 fix(refs DPLAN-16159): add more prosemirror packages to resolutions
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug, dependencies

#1340 feat: add tests for DpCheckboxGroup
  src/components/DpCheckboxGroup/DpCheckboxGroup.vue
  tests/form/DpCheckboxGroup.spec.js
Labels: bug, enhancement, review:frontend
