Repository demos-europe/demosplan-ui, pull requests merged in 2025-03, with the labels that each got.

#1203 fix: Type-o in DpTreeListNode
  CHANGELOG.md
  src/components/DpTreeList/DpTreeListNode.vue
Labels: bug

#1202 fix: Catch Full-width in dpFormRow
  CHANGELOG.md
  src/components/DpFormRow/DpFormRow.vue
Labels: bug

#1204 fix(refs DPLAN-15153): fix imports for mention extension [vue 3]
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
  src/components/DpEditor/libs/editorCustomInsert.js
  src/components/DpEditor/libs/tiptapExtensions.js
Labels: bug, review:frontend

#1209 fix: Escape multiline break chars
  CHANGELOG.md
  src/components/DpButton/DpButton.vue
Labels: bug

#1215 chore(refs DPLAN-12921): Reintroduce clickOutside
  CHANGELOG.md
  package.json
  src/components/DpFlyout/DpFlyout.vue
  src/components/DpSplitButton/DpSplitButton.vue
  src/components/DpTimePicker/DpTimePicker.vue
  yarn.lock
Labels: enhancement, review:frontend

#1214 fix(refs DPLAN-15151): Propperly emit checkboxGroup events
  CHANGELOG.md
  src/components/DpCheckboxGroup/DpCheckboxGroup.vue
  src/components/DpEditableList/DpEditableList.vue
Labels: bug

#1208 fix(refs DPLAN-15186): Remove useless wrapping div
  CHANGELOG.md
  src/components/DpMultiselect/DpMultiselect.vue
Labels: bug

#1217 fix(refs DPLAN-15169): fix image upload in DpEditor
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
  src/components/DpEditor/DpResizableImage.vue
  src/components/DpEditor/DpUploadModal.vue
  src/components/DpTransitionExpand/DpTransitionExpand.vue
  src/components/DpUploadFiles/DpUpload.vue
  src/components/DpUploadFiles/DpUploadFiles.vue
  src/components/DpUploadFiles/DpUploadedFile.vue
  src/components/DpUploadFiles/DpUploadedFileList.vue
Labels: bug, review:frontend

#1220 b(refs: DPLAN-13110) changed emitvalue to pass obscure tag
  CHANGELOG.md
  src/components/DpEditor/DpEditor.vue
Labels: review:frontend
