Repository demos-europe/demosplan-ui, pull requests merged in 2025-01, with the labels that each got.

#1080 feat (refs DPLAN-3217 AB#12115): Refactor editable list
  CHANGELOG.md
  src/components/DpEditableList/DpEditableList.vue
Labels: enhancement, review:frontend

#1144 chore: Add drop space for DpTreeList
  CHANGELOG.md
  src/components/DpTreeList/DpTreeListNode.vue
Labels: bug, enhancement

#937 chor (refs DPLAN-11885): add Jest Test for the DpBadge component.
  src/components/DpDataTable/DpTableRow.vue
  tests/DpBadge.spec.js
  yarn.lock
Labels: enhancement, review:frontend

#1147 fix(refs DPLAN-12969): Allow setting the width of the search field
  CHANGELOG.md
  src/components/DpSearchField/DpSearchField.vue
Labels: bug, review:frontend

#1145 feat(refs DPLAN-12969,#AB21841): Add new styling to filter flyout
  CHANGELOG.md
  src/components/DpFlyout/DpFlyout.vue
Labels: review:frontend

#1157 build: add missing dependency [vue 3]
  CHANGELOG.md
  package.json
  yarn.lock
Labels: bug, review:frontend

#1139 test(refs DPLAN-12969): add unit test for DpFlyout
  CHANGELOG.md
  tests/components/DpFlyout.spec.js
Labels: review:frontend
